[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "benchrun"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = ["aiohttp==3.10.10", "PyYAML==6.0.2"]

[project.optional-dependencies]
dev = ["pytest==8.3.3", "pytest-asyncio==0.24.0", "pytest-aiohttp==1.0.5"]

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
testpaths = ["tests"]
pythonpath = ["."]

[tool.setuptools.packages.find]
include = ["benchrun*", "report*"]
